name: Test detection regex for bypass
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Run dedicated test case
      run: mvn -D"test=DetectionRegexBypassTest" -B clean test --file sandbox/pom.xml
